# Generated by Django 4.2.5 on 2023-09-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carName", models.CharField(max_length=255)),
                ("carOwner", models.CharField(max_length=50)),
                ("licensePlate", models.CharField(max_length=7)),
                ("dateTime", models.DateTimeField(auto_now=True)),
                (
                    "imageCar",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameGarage", models.CharField(max_length=255)),
                (
                    "adressGarage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "imageGarage",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
            },
        ),
        migrations.CreateModel(
            name="CarsInGarage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCar", models.ManyToManyField(to="parkitu.car")),
                (
                    "idGarage",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carInGarage",
                        to="parkitu.garage",
                    ),
                ),
            ],
            options={
                "verbose_name": "CarsInGarage",
                "verbose_name_plural": "CarsInGarages",
            },
        ),
    ]
