# Generated by Django 4.2.3 on 2023-08-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carName", models.CharField(max_length=50)),
                ("carOwner", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameGarage", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
            },
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licensePlate", models.CharField(max_length=7)),
                ("date", models.DateField()),
                ("firstTime", models.TimeField()),
                ("lastTime", models.TimeField()),
                (
                    "carName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_name_details",
                        to="parkitu.car",
                    ),
                ),
                (
                    "carOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_owner_details",
                        to="parkitu.car",
                    ),
                ),
                (
                    "nameGarage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="garage_details",
                        to="parkitu.garage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail",
                "verbose_name_plural": "Details",
            },
        ),
    ]
