# Generated by Django 4.2.4 on 2023-08-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carName", models.CharField(max_length=255)),
                ("carOwner", models.CharField(max_length=50)),
                ("licensePlate", models.CharField(max_length=7)),
                ("dateTime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameGarage", models.CharField(max_length=255)),
                (
                    "adressGarage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
            },
        ),
        migrations.CreateModel(
            name="CarsInGarage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idCar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carsInGarage",
                        to="parkitu.car",
                    ),
                ),
                (
                    "idGarage",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carInGarage",
                        to="parkitu.garage",
                    ),
                ),
            ],
            options={
                "verbose_name": "CarsInGarage",
                "verbose_name_plural": "CarsInGarages",
            },
        ),
    ]
