# Generated by Django 4.2.6 on 2023-10-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="dateTime",
        ),
        migrations.AddField(
            model_name="car",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
