# Generated by Django 4.2.3 on 2023-08-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="nameGarage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="name_garage_details",
                to="parkitu.garage",
            ),
        ),
    ]
