# Generated by Django 4.2.6 on 2023-10-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0002_remove_car_datetime_car_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carOwnerPhone",
            field=models.CharField(default="Seu-valor-padrão-aqui", max_length=15),
        ),
    ]
