# Generated by Django 4.2.4 on 2023-08-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("parkitu", "0002_car_imagecar"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="imageGarage",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
