# Generated by Django 4.2.4 on 2023-08-07 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0002_alter_detail_namegarage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Detail",
        ),
        migrations.DeleteModel(
            name="Garage",
        ),
    ]
