# Generated by Django 4.2.4 on 2023-08-07 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0003_delete_detail_delete_garage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Car",
            new_name="Cars",
        ),
    ]
