# Generated by Django 4.2.6 on 2023-10-24 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0004_alter_car_carownerphone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="carOwnerPhone",
            new_name="carownerphone",
        ),
    ]
