# Generated by Django 4.2.4 on 2023-08-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0004_rename_car_cars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameGarage", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
            },
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licensePlate", models.CharField(max_length=7)),
                ("date", models.DateField()),
                ("firstTime", models.TimeField()),
                ("lastTime", models.TimeField()),
                (
                    "carName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_name_details",
                        to="parkitu.cars",
                    ),
                ),
                (
                    "carOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_owner_details",
                        to="parkitu.cars",
                    ),
                ),
                (
                    "nameGarage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="name_garage_details",
                        to="parkitu.garages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail",
                "verbose_name_plural": "Details",
            },
        ),
    ]
