# Generated by Django 4.2.6 on 2023-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0005_rename_carownerphone_car_carownerphone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="carownerphone",
        ),
        migrations.AddField(
            model_name="car",
            name="carOwnerPhone",
            field=models.CharField(default="Seu-valor-padrão-aqui", max_length=20),
        ),
    ]
