# Generated by Django 4.2.4 on 2023-08-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0005_garages_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="licensePlate",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="garages",
            name="adressGarage",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="details",
            name="licensePlate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="license_plate_details",
                to="parkitu.cars",
            ),
        ),
        migrations.AlterField(
            model_name="garages",
            name="nameGarage",
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
