# Generated by Django 4.2.4 on 2023-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0006_cars_licenseplate_garages_adressgarage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="date",
            field=models.DateField(default="Data"),
        ),
        migrations.AddField(
            model_name="cars",
            name="firstTime",
            field=models.TimeField(default="Horário de entrada"),
        ),
        migrations.AddField(
            model_name="cars",
            name="lastTime",
            field=models.TimeField(default="Horário de Saída"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="carName",
            field=models.CharField(default="Nome do Carro", max_length=50),
        ),
        migrations.AlterField(
            model_name="cars",
            name="carOwner",
            field=models.CharField(default="Dono do Carro", max_length=50),
        ),
        migrations.AlterField(
            model_name="cars",
            name="licensePlate",
            field=models.CharField(default="PLaca do Carro", max_length=7),
        ),
        migrations.AlterField(
            model_name="garages",
            name="adressGarage",
            field=models.CharField(
                blank=True, default="Endereço da Garagem", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="garages",
            name="nameGarage",
            field=models.CharField(default="Nome da Garagem", max_length=100),
        ),
        migrations.DeleteModel(
            name="Details",
        ),
    ]
