# Generated by Django 4.2.4 on 2023-08-08 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0007_cars_date_cars_firsttime_cars_lasttime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="date",
        ),
    ]
