# Generated by Django 4.2.4 on 2023-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0008_remove_cars_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="carName",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cars",
            name="carOwner",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cars",
            name="firstTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="cars",
            name="lastTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="cars",
            name="licensePlate",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="garages",
            name="adressGarage",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="garages",
            name="nameGarage",
            field=models.CharField(max_length=100),
        ),
    ]
