# Generated by Django 4.2.4 on 2023-08-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0010_car_garage_delete_cars_delete_garages"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarsInGarage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idCar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars_garages",
                        to="parkitu.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "CarsInGarage",
                "verbose_name_plural": "CarsInGarages",
            },
        ),
    ]
