# Generated by Django 4.2.4 on 2023-08-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0011_carsingarage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={},
        ),
        migrations.AlterModelOptions(
            name="garage",
            options={"verbose_name": "Car", "verbose_name_plural": "Cars"},
        ),
        migrations.AddField(
            model_name="carsingarage",
            name="idGarage",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carInGarage",
                to="parkitu.garage",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="carsingarage",
            name="idCar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carsInGarage",
                to="parkitu.car",
            ),
        ),
    ]
