# Generated by Django 4.2.7 on 2023-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0012_remove_car_carownerphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carOwnerPhone",
            field=models.CharField(default="123456789", max_length=15),
        ),
    ]
