# Generated by Django 4.2.7 on 2023-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0014_remove_car_carownerphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carOwnerPhone",
            field=models.CharField(blank=True, default="123456789", max_length=15),
        ),
    ]
