# Generated by Django 4.2.7 on 2023-11-21 17:17

from django.db import migrations, models
import parkitu.models


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0015_car_carownerphone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="carOwnerPhone",
            field=models.CharField(
                blank=True,
                default="123456789",
                max_length=15,
                validators=[parkitu.models.validate_carownerphone_length],
            ),
        ),
    ]
