# Generated by Django 4.2.7 on 2023-11-21 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkitu", "0016_alter_car_carownerphone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="carOwnerPhone",
        ),
    ]
